#!/usr/bin/env python3
"""Regenerate ``certior/_lean_binary_manifest.py`` from built Lean binaries.

Run this at release time, after building ``certior-flow-check`` on each
target platform and collecting the artifacts into one directory. It computes
each artifact's SHA-256 + size and writes them into the manifest that
``certior-install-lean`` verifies downloads against.

Workflow::

    # 1. Build on each platform (CI matrix or by hand), naming the outputs:
    #      dist/lean-binaries/certior-flow-check-linux-x86_64
    #      dist/lean-binaries/certior-flow-check-macos-arm64
    #      dist/lean-binaries/certior-flow-check-macos-x86_64
    # 2. Regenerate the manifest:
    python scripts/prepare-lean-release.py --tag lean-binary-v0.1.0a1
    # 3. Commit certior/_lean_binary_manifest.py
    # 4. Create the GitHub Release with that tag and upload the artifacts.

CI can run ``--check`` to fail the build if the committed manifest does not
match the artifacts on disk::

    python scripts/prepare-lean-release.py --tag <tag> --check
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "certior" / "_lean_binary_manifest.py"
DEFAULT_ARTIFACT_DIR = REPO_ROOT / "dist" / "lean-binaries"

# Platform keys must match certior.lean_installer.platform_key().
PLATFORMS = ["linux-x86_64", "macos-arm64", "macos-x86_64"]
REPO_SLUG = "paulinebourigault/certior"


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _fingerprint() -> str:
    sys.path.insert(0, str(REPO_ROOT))
    try:
        from certior._lean_fingerprint import FINGERPRINT

        return FINGERPRINT
    except ImportError:
        return "unknown"


def _collect(artifact_dir: Path) -> dict:
    """Build the ``{platform: entry|None}`` map from artifacts on disk."""
    entries: dict = {}
    for key in PLATFORMS:
        path = artifact_dir / f"certior-flow-check-{key}"
        if path.is_file():
            entries[key] = {
                "filename": path.name,
                "sha256": _sha256(path),
                "size": path.stat().st_size,
            }
        else:
            entries[key] = None
    return entries


def _render(tag: str, fingerprint: str, entries: dict) -> str:
    lines = []
    for key in PLATFORMS:
        e = entries[key]
        if e is None:
            lines.append(f'    "{key}": None,')
        else:
            lines.append(f'    "{key}": {{')
            lines.append(f'        "filename": "{e["filename"]}",')
            lines.append(
                f'        "sha256": "{e["sha256"]}",  # pragma: allowlist secret'
            )
            lines.append(f'        "size": {e["size"]},')
            lines.append("    },")
    body = "\n".join(lines)
    return f'''"""Baked-in manifest of published ``certior-flow-check`` Lean binaries.

The pip wheel does not bundle the ~90 MB Lean live-verification binary
(see ``scripts/build-lean-binary.sh``). Instead, ``certior-install-lean``
downloads the binary for the current platform from a GitHub Release and
verifies it against the trusted SHA-256 recorded here.

Security model: this manifest ships *inside* the pip package, so it is as
trusted as the rest of the installed code. The binary is fetched over the
network (untrusted transport) and is only installed if its SHA-256 matches
the value below. A tampered or truncated download fails closed.

GENERATED by ``scripts/prepare-lean-release.py`` — do not hand-edit. Rebuild
the binaries, rerun the script, and commit the result with the GitHub Release.
"""
from __future__ import annotations

from typing import Dict, Optional, TypedDict

# GitHub ``owner/repo`` that hosts the release assets.
REPO = "{REPO_SLUG}"

# Release tag under which the binaries are published as assets:
#   https://github.com/{{REPO}}/releases/download/{{RELEASE_TAG}}/{{filename}}
RELEASE_TAG = "{tag}"

# stdin/stdout JSON protocol version the binary speaks (the value it returns
# in its ready handshake).
PROTOCOL_VERSION = "1.0.0"

# Lean policy-model fingerprint the published binaries were built against.
# Must match ``certior._lean_fingerprint.FINGERPRINT``.
POLICY_FINGERPRINT = "{fingerprint}"  # pragma: allowlist secret


class BinaryEntry(TypedDict):
    """A single published binary artifact."""

    filename: str
    sha256: str
    size: int


# Platform key -> published artifact, or ``None`` when no binary is published
# yet for that platform.
BINARIES: Dict[str, Optional[BinaryEntry]] = {{
{body}
}}


def entry_for(platform_key: str) -> Optional[BinaryEntry]:
    """Return the published artifact for ``platform_key``, or ``None``."""
    return BINARIES.get(platform_key)


def download_url(entry: BinaryEntry) -> str:
    """GitHub Release asset URL for a manifest entry."""
    return (
        f"https://github.com/{{REPO}}/releases/download/"
        f"{{RELEASE_TAG}}/{{entry['filename']}}"
    )
'''


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tag",
        required=True,
        help="GitHub Release tag the binaries are published under",
    )
    parser.add_argument(
        "--artifacts",
        type=Path,
        default=DEFAULT_ARTIFACT_DIR,
        help=f"directory of built binaries (default: {DEFAULT_ARTIFACT_DIR})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed manifest matches the artifacts; do not write",
    )
    args = parser.parse_args(argv)

    if not args.artifacts.is_dir():
        print(f"error: artifact dir not found: {args.artifacts}", file=sys.stderr)
        return 2

    entries = _collect(args.artifacts)
    found = [k for k, v in entries.items() if v]
    if not found:
        print(
            f"error: no certior-flow-check-* artifacts in {args.artifacts}",
            file=sys.stderr,
        )
        return 2

    rendered = _render(args.tag, _fingerprint(), entries)

    if args.check:
        current = MANIFEST.read_text() if MANIFEST.exists() else ""
        if current.strip() != rendered.strip():
            print(
                "error: _lean_binary_manifest.py is out of date with the "
                "artifacts. Re-run scripts/prepare-lean-release.py.",
                file=sys.stderr,
            )
            return 1
        print(f"manifest up to date ({', '.join(found)})")
        return 0

    MANIFEST.write_text(rendered)
    print(f"wrote {MANIFEST.relative_to(REPO_ROOT)} for tag {args.tag}")
    for k in PLATFORMS:
        e = entries[k]
        status = f"{e['sha256'][:12]}… ({e['size'] / 1e6:.0f} MB)" if e else "(none)"
        print(f"  {k:14} {status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
