#!/usr/bin/env python3
"""Regenerate ``certior/_lean_fingerprint.py`` from the Lean source.

Run when the Lean source under ``lean4/CertiorLattice/Certior/`` changes
so that pip-installed users continue to receive a real fingerprint:

    python scripts/update-lean-fingerprint.py

CI runs the same script in check mode and fails the build if the file
on disk does not match the current Lean source:

    python scripts/update-lean-fingerprint.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEAN_DIR = REPO_ROOT / "lean4" / "CertiorLattice" / "Certior"
TARGET = REPO_ROOT / "certior" / "_lean_fingerprint.py"

HEADER = '''"""Lean-audited policy-model fingerprint baked at wheel-build time.

This module is generated by ``scripts/update-lean-fingerprint.py`` from the
contents of ``lean4/CertiorLattice/Certior/*.lean``. It exists so that
pip-installed users (who do not have the Lean source on disk) still get a
real fingerprint in their certificates and policy attestation, rather than
the ``"unknown"`` placeholder that the runtime computation falls back to
when no Lean source is reachable.

When the Lean source changes, regenerate this file with::

    python scripts/update-lean-fingerprint.py

The regeneration script asserts that the fingerprint matches the one
produced by hashing the Lean source files on disk. CI runs the same
script in check-only mode so a Lean change that does not regenerate the
constant fails the build.
"""

FINGERPRINT = "{fingerprint}"
'''


def compute_fingerprint() -> str:
    if not LEAN_DIR.exists():
        sys.exit(
            f"Lean source directory not found at {LEAN_DIR}. "
            "Run this script from a source checkout."
        )
    h = hashlib.sha256()
    for f in sorted(LEAN_DIR.glob("*.lean")):
        h.update(f.name.encode() + b"\0")
        h.update(f.read_bytes())
    return h.hexdigest()[:16]


def read_current_constant() -> str | None:
    if not TARGET.exists():
        return None
    namespace: dict = {}
    exec(TARGET.read_text(), namespace)
    return namespace.get("FINGERPRINT")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail with non-zero exit if the file on disk is stale.",
    )
    args = parser.parse_args()

    live = compute_fingerprint()
    current = read_current_constant()

    if args.check:
        if live == current:
            print(f"OK: fingerprint up to date ({live}).")
            return 0
        print(
            f"FAIL: {TARGET.relative_to(REPO_ROOT)} is stale.\n"
            f"  on disk:   {current!r}\n"
            f"  computed:  {live!r}\n"
            f"Run: python scripts/update-lean-fingerprint.py",
            file=sys.stderr,
        )
        return 1

    if live == current:
        print(f"No change ({live}).")
        return 0
    TARGET.write_text(HEADER.format(fingerprint=live))
    print(f"Updated {TARGET.relative_to(REPO_ROOT)}: {current!r} -> {live!r}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
