"""Lean-audited policy-model fingerprint baked at wheel-build time.

This module is generated by ``scripts/update-lean-fingerprint.py`` from the
contents of ``lean4/CertiorLattice/Certior/*.lean``. It exists so that
pip-installed users (who do not have the Lean source on disk) still get a
real fingerprint in their certificates and policy attestation, rather than
the ``"unknown"`` placeholder that the runtime computation falls back to
when no Lean source is reachable.

When the Lean source changes, regenerate this file with::

    python scripts/update-lean-fingerprint.py

The regeneration script asserts that the fingerprint matches the one
produced by hashing the Lean source files on disk. CI runs the same
script in check-only mode so a Lean change that does not regenerate the
constant fails the build.
"""

FINGERPRINT = "cc3e0c7431fd8a53"
