"""Baked-in manifest of published ``certior-flow-check`` Lean binaries.

The pip wheel does not bundle the ~90 MB Lean live-verification binary
(see ``scripts/build-lean-binary.sh``). Instead, ``certior-install-lean``
downloads the binary for the current platform from a GitHub Release and
verifies it against the trusted SHA-256 recorded here.

Security model: this manifest ships *inside* the pip package, so it is as
trusted as the rest of the installed code. The binary is fetched over the
network (untrusted transport) and is only installed if its SHA-256 matches
the value below. A tampered or truncated download fails closed.

GENERATED by ``scripts/prepare-lean-release.py`` — do not hand-edit. Rebuild
the binaries, rerun the script, and commit the result with the GitHub Release.
"""
from __future__ import annotations

from typing import Dict, Optional, TypedDict

# GitHub ``owner/repo`` that hosts the release assets.
REPO = "paulinebourigault/certior"

# Release tag under which the binaries are published as assets:
#   https://github.com/{REPO}/releases/download/{RELEASE_TAG}/{filename}
RELEASE_TAG = "lean-binary-v0.1.0a1"

# stdin/stdout JSON protocol version the binary speaks (the value it returns
# in its ready handshake).
PROTOCOL_VERSION = "1.0.0"

# Lean policy-model fingerprint the published binaries were built against.
# Must match ``certior._lean_fingerprint.FINGERPRINT``.
POLICY_FINGERPRINT = "cc3e0c7431fd8a53"  # pragma: allowlist secret


class BinaryEntry(TypedDict):
    """A single published binary artifact."""

    filename: str
    sha256: str
    size: int


# Platform key -> published artifact, or ``None`` when no binary is published
# yet for that platform.
BINARIES: Dict[str, Optional[BinaryEntry]] = {
    "linux-x86_64": {
        "filename": "certior-flow-check-linux-x86_64",
        "sha256": "8e626271101f475e32fc978926342d666fc940a551c8be69482010c0597abe7c",  # pragma: allowlist secret
        "size": 93476576,
    },
    "macos-arm64": {
        "filename": "certior-flow-check-macos-arm64",
        "sha256": "31271e64ef36f6dea221b41161626a563dab02d38a67af40157d53e2e8af88fc",  # pragma: allowlist secret
        "size": 79097904,
    },
    "macos-x86_64": None,
}


def entry_for(platform_key: str) -> Optional[BinaryEntry]:
    """Return the published artifact for ``platform_key``, or ``None``."""
    return BINARIES.get(platform_key)


def download_url(entry: BinaryEntry) -> str:
    """GitHub Release asset URL for a manifest entry."""
    return (
        f"https://github.com/{REPO}/releases/download/"
        f"{RELEASE_TAG}/{entry['filename']}"
    )
